name: task_manager
description: "A task manager with timers and dates."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  icons_plus: ^5.0.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

dev_dependencies:
  flutter_lints: ^5.0.0
